/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import DAO.ClientesDAO;
import Modelos.Cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author Henrick
 */
public class Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblContato = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        txtContato = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        btnSair = new javax.swing.JButton();
        BtnAlterar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblNome.setText("Nome :");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        lblCpf.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblCpf.setText("Cpf : ");
        getContentPane().add(lblCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        lblContato.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblContato.setText("Contato :");
        getContentPane().add(lblContato, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        lblCidade.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblCidade.setText("Cidade :");
        getContentPane().add(lblCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, -1));

        lblEndereco.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblEndereco.setText("Endereço :");
        getContentPane().add(lblEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        txtCpf.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        getContentPane().add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 210, -1));

        txtContato.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        getContentPane().add(txtContato, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 200, -1));

        txtCidade.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        getContentPane().add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 180, -1));

        txtNome.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 220, -1));

        txtEndereco.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        getContentPane().add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 460, -1));

        btnSair.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 120, -1));

        BtnAlterar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        BtnAlterar.setText("Limpar");
        BtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 120, -1));

        btnCadastrar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 120, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_btnSairActionPerformed

    private void BtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlterarActionPerformed
        // TODO add your handling code here:
        
        txtNome.setText("");
txtCpf.setText("");
txtContato.setText("");
txtCidade.setText("");
txtEndereco.setText("");


    }//GEN-LAST:event_BtnAlterarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
  Cliente clientes = new Cliente();
clientes.setNome(txtNome.getText());
clientes.setCpf(txtCpf.getText());
clientes.setContato(txtContato.getText());
clientes.setCidade(txtCidade.getText());
clientes.setEndereco(txtEndereco.getText());

if ((txtNome.getText().isEmpty()) || (txtCpf.getText().isEmpty()) || (txtContato.getText().isEmpty()) || (txtCidade.getText().isEmpty())|| (txtEndereco.getText().isEmpty())) {
   JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
}
else {

    
    ClientesDAO dao = new ClientesDAO();
    dao.adiciona(clientes);
    JOptionPane.showMessageDialog(null, "Cliente "+txtNome.getText()+" inserido com sucesso! ");
}


txtNome.setText("");
txtCpf.setText("");
txtContato.setText("");
txtCidade.setText("");
txtEndereco.setText("");
        
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblContato;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtContato;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
