/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import DAO.FuncionariosDAO;
import Modelos.Funcionario;
import javax.swing.JOptionPane;

/**
 *
 * @author Henrick
 */
public class Funcionarios extends javax.swing.JFrame {

    /**
     * Creates new form Funcionarios
     */
    public Funcionarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDadospessoais = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        Contato = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblDadosprofissionais = new javax.swing.JLabel();
        lblCargonaempresa = new javax.swing.JLabel();
        lblHorassemanais = new javax.swing.JLabel();
        lblSaidaentrada = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtContato = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtCargonaempresa = new javax.swing.JTextField();
        txtHorassemanais = new javax.swing.JTextField();
        txtEntradasaida = new javax.swing.JTextField();
        btnSair = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDadospessoais.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblDadospessoais.setText("Dados Pessoais :");
        getContentPane().add(lblDadospessoais, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        lblNome.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblNome.setText("Nome :");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 188, -1, 20));

        lblCpf.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblCpf.setText("Cpf :");
        getContentPane().add(lblCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 188, -1, 20));

        lblEndereco.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblEndereco.setText("Endereco :");
        getContentPane().add(lblEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        Contato.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Contato.setText("Contato :");
        getContentPane().add(Contato, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        lblEmail.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblEmail.setText("E-mail :");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        lblDadosprofissionais.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblDadosprofissionais.setText("Dados Profissionais :");
        getContentPane().add(lblDadosprofissionais, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        lblCargonaempresa.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblCargonaempresa.setText("Cargo na Empresa :");
        getContentPane().add(lblCargonaempresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        lblHorassemanais.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblHorassemanais.setText("Horas Semanai :");
        getContentPane().add(lblHorassemanais, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        lblSaidaentrada.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSaidaentrada.setText("Entrada - Saída :");
        getContentPane().add(lblSaidaentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        txtCpf.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 186, 180, -1));

        txtNome.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 186, 250, -1));

        txtEndereco.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 220, -1));

        txtContato.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(txtContato, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 150, -1));

        txtEmail.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 320, -1));

        txtCargonaempresa.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(txtCargonaempresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 230, -1));

        txtHorassemanais.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(txtHorassemanais, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 250, -1));

        txtEntradasaida.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(txtEntradasaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 250, -1));

        btnSair.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 100, -1));

        btnAlterar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnAlterar.setText("Limpar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 100, -1));

        btnCadastrar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 100, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        
        txtNome.setText("");
txtCpf.setText("");
txtContato.setText("");
txtEndereco.setText("");
txtEmail.setText("");
txtCargonaempresa.setText("");
txtHorassemanais.setText("");
txtEntradasaida.setText("");
        
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        Funcionario funcionario = new Funcionario();
funcionario.setNome(txtNome.getText());
funcionario.setCpf(txtCpf.getText());
funcionario.setEndereco(txtEndereco.getText());
funcionario.setContato(txtContato.getText());
funcionario.setEmail(txtEmail.getText());
funcionario.setCargonaempresa(txtCargonaempresa.getText());
funcionario.setHorassemanais(txtHorassemanais.getText());
funcionario.setEntradasaida(txtEntradasaida.getText());

if ((txtNome.getText().isEmpty()) || (txtCpf.getText().isEmpty()) || (txtEndereco.getText().isEmpty()) || (txtContato.getText().isEmpty())|| (txtEmail.getText().isEmpty()) || (txtCargonaempresa.getText().isEmpty()) || (txtHorassemanais.getText().isEmpty()) || (txtEntradasaida.getText().isEmpty())) {
   JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
}
else {

    
    FuncionariosDAO dao = new FuncionariosDAO();
    dao.adiciona(funcionario);
    JOptionPane.showMessageDialog(null, "funcionario "+txtNome.getText()+" inserido com sucesso! ");
}


txtNome.setText("");
txtCpf.setText("");
txtContato.setText("");
txtEndereco.setText("");
txtEmail.setText("");
txtCargonaempresa.setText("");
txtHorassemanais.setText("");
txtEntradasaida.setText("");
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funcionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contato;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCargonaempresa;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDadospessoais;
    private javax.swing.JLabel lblDadosprofissionais;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblHorassemanais;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSaidaentrada;
    private javax.swing.JTextField txtCargonaempresa;
    private javax.swing.JTextField txtContato;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEntradasaida;
    private javax.swing.JTextField txtHorassemanais;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
