/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;


import DAO.FuncionariosDAO;
import Modelos.tbl_funcionario;
import javax.swing.JOptionPane;

/**
 *
 * @author Henrick
 */
public class Funcionario extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public Funcionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblContato = new javax.swing.JLabel();
        lblRua = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblCidade2 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        txtContato = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtRua = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        btnSair = new javax.swing.JButton();
        BtnAlterar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSenha = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblNome.setText("Nome :");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        lblCpf.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblCpf.setText("Cpf : ");
        getContentPane().add(lblCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        lblContato.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblContato.setText("Contato :");
        getContentPane().add(lblContato, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        lblRua.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblRua.setText("Rua :");
        getContentPane().add(lblRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        lblBairro.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblBairro.setText("Bairro :");
        getContentPane().add(lblBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        lblNumero.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblNumero.setText("N:");
        getContentPane().add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        lblCidade2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblCidade2.setText("Cidade :");
        getContentPane().add(lblCidade2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        txtCpf.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        getContentPane().add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 210, -1));

        txtContato.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        getContentPane().add(txtContato, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 190, -1));

        txtNumero.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 60, -1));

        txtNome.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 220, -1));

        txtRua.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        getContentPane().add(txtRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 210, -1));

        txtCidade.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        getContentPane().add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 180, -1));

        txtBairro.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        getContentPane().add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 120, -1));

        btnSair.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 120, -1));

        BtnAlterar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        BtnAlterar.setText("Limpar");
        BtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 120, -1));

        btnCadastrar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 120, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Senha:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 284, 70, 50));

        jSenha.setText("jPasswordField1");
        getContentPane().add(jSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 480, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        dispose();

    }//GEN-LAST:event_btnSairActionPerformed

    private void BtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlterarActionPerformed
        // TODO add your handling code here:

        txtNome.setText("");
        txtCpf.setText("");
        jSenha.setText("");
        txtContato.setText("");
        txtNumero.setText("");
        txtRua.setText("");
        txtCidade.setText("");
        txtBairro.setText("");
    }//GEN-LAST:event_BtnAlterarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
         tbl_funcionario tbl_funcionario = new tbl_funcionario ();
        tbl_funcionario.setNome(txtNome.getText());
        tbl_funcionario.setCpf(txtCpf.getText());
        tbl_funcionario.setSenha(String.valueOf(jSenha.getPassword()));
        tbl_funcionario.setContato(txtContato.getText());
        tbl_funcionario.setCidade(txtCidade.getText());
        tbl_funcionario.setRua(txtRua.getText());
        tbl_funcionario.setBairro(txtBairro.getText());
        tbl_funcionario.setNumero(txtNumero.getText());

        if ((txtNome.getText().isEmpty()) || (txtCpf.getText().isEmpty()) || (String.valueOf(jSenha.getPassword()).isEmpty()) || (txtContato.getText().isEmpty()) || (txtNumero.getText().isEmpty()) || (txtRua.getText().isEmpty()) || (txtBairro.getText().isEmpty()) || (txtCidade.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
        } else {

            FuncionariosDAO dao = new FuncionariosDAO();
            dao.adiciona(tbl_funcionario);
            JOptionPane.showMessageDialog(null, "Funcionario " + txtNome.getText() + " inserido com sucesso! ");
        }
        txtNome.setText("");
        txtCpf.setText("");
        txtContato.setText("");
        txtNumero.setText("");
        txtRua.setText("");
        txtCidade.setText("");
        txtBairro.setText("");

    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funcionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jSenha;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCidade2;
    private javax.swing.JLabel lblContato;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRua;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtContato;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRua;
    // End of variables declaration//GEN-END:variables
}
